name: Deploy Static Site
on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install mkdocs-material mkdocs

      - name: Build MkDocs site
        # source ফোল্ডারে ঢুকে বিল্ড করে রেজাল্ট 'public' ফোল্ডারে সেভ করবে
        run: cd source && mkdocs build --site-dir ../public

      - name: Deploy to SourceCraft Pages
        uses: sourcecraft/pages-deploy-action@v1
        with:
          folder: public