site_name: Портфолио - Сагор
theme:
  name: material
  language: ru
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Темная тема
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Светлая тема
  # Добавил простое расширение для красивых блоков с текстом
  markdown_extensions:
    - admonition

nav:
  - Главная: index.md
  - Об авторе: about.md
  - Лабораторные работы:
      - Лабораторная работа 1: labs/lab1.md
      - Лабораторная рабоcdта 2: labs/lab2.md
      - Лабораторная работа 3: labs/lab3.md
      - Лабораторная работа 4: labs/lab4.md
      - Лабораторная работа 5: labs/lab5.md
      - Template: template.md
# Подключение расширения для использования эмодзи и иконок
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
